version: '3.1'

services:
  mysql:  
    image: mysql:5.7
    container_name: abby-mysql
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=abbyrootpassword
      - MYSQL_DATABASE=abby
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=devpassword
    restart: unless-stopped
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: abby-app
    hostname: api.abbykadabby.com
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - mysql

volumes:
  mysql-data:

networks:
  default: