version: '3.1'

services:
  mysql:  
    build: 
      context: .
      dockerfile: Dockerfile-db
    container_name: freshtomatoes-db
    hostname: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=freshtomatoes
      - MYSQL_DATABASE=freshtomatoes
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=devpassword
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/etc/mysql

  web:
    build: .
    container_name: freshtomatoes-web
    hostname: www.freshtomatoes.com
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html/
    ports:
      - "80:80"
    depends_on:
      - mysql

  api:
    build: .
    container_name: freshtomatoes-api
    hostname: api.freshtomatoes.com
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html/
    ports:
      - "81:81"
    depends_on:
      - mysql

volumes:
  mysql-data:

networks:
  default:
